# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzflUCE2IGoX5BFAHOK0aXpJxfkwVo83
"""

import streamlit as st
from PIL import Image, ImageOps
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
from tensorflow.keras import preprocessing
from tensorflow.keras.models import load_model
from tensorflow.keras.activations import softmax
import os

def main():
  file_uploaded = st.file_uploader("Choose the image of blood cell", type = ['jpg', 'bmp', 'png', 'jpeg'])
  if file_uploaded is not None:
    image = Image.open(file_uploaded)
    figure = plt.figure()
    plt.imshow(image)
    plt.axis('off')
    result = predict_class(image)
    st.write(result)
    st.pyplot(figure)

def predict_class(image):
  classifier_model = tf.keras.models.load_model('model.hdf5')
  shape = ((128,128,3))
  model = tf.keras.Sequential([hub.KerasLayer(classifier_model, input_shape=shape)])
  test_image = image.resize((128,128))
  test_image = preprocessing.image.img_to_array(test_image)
  test_image = test_image/255.0
  test_image = np.expand_dims(test_image, axis = 0)
  class_names = ['all',
                 'hem']
  predictions = model.predict(test_image)
  scores = tf.nn.softmax(predictions[0])
  scores = scores.numpy()
  image_class = class_names[np.argmax(scores)]
  if image_class == "all":
    result = "It is a leukemic B-lymphoblast cell"
  elif image_class == "hem":
    result = "It is a normal cell"
    
  return result

if __name__ == "__main__":
  main()